name: Model Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Считаем lowercase имя для GHCR: ghcr.io/supermba/ml-deployment
      - name: Compute image name (lowercase)
        shell: bash
        run: |
          echo "IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "IMAGE_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "Will push to: $IMAGE_REPO"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_REPO }}:latest

  smoke-test:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Compute image name (lowercase)
        shell: bash
        run: |
          echo "IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "IMAGE_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run container (smoke)
        run: |
          docker run -d --name ml -p 8080:8080 -e MODEL_VERSION=${{ secrets.MODEL_VERSION }} ${{ env.IMAGE_REPO }}:${{ env.IMAGE_SHA }}
          sleep 3
          curl -sS http://127.0.0.1:8080/health
          echo
          curl -sS -X POST http://127.0.0.1:8080/predict -H "Content-Type: application/json" -d '{"x":[1,2,3]}'
          echo

  deploy-render:
    runs-on: ubuntu-latest
    needs: smoke-test
    steps:
      - name: Trigger deploy on Render (Deploy Hook)
        run: |
          curl -sS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

